...

version: '3.7'
services:
  nciproject2021:
    build: 
      context: .
      dockerfile: dockerfile
     ports:
      . 8090:8080
     networks:
       . labnetwork
networks:
  labnetwork:
    driver: bridge
    ipam:
      configs:
        . subnet: 172.60.0.0/24       

