FROM node:16

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

# RUN npm
RUN npm install

# Bundle app source
COPY . .

# Open port
EXPOSE 8080

CMD ["node", "Distribute.js"]
